"""
Template for the COMP1730/6730 project assignment, S2 2020.
The assignment specification is available on the course web site:
https://cs.anu.edu.au/courses/comp1730/assessment/project/

The assignment is due 25/10/2020 at 11.55 pm, Canberra time.

Collaborators: <list the UIDs of ALL members of your project group here>
"""

def analyse(path_to_file):
    pass


# The section below will be executed when you run this file.
# Use it to run tests of your analysis function on the data
# files provided. You can comment/uncomment tests if you want.

if __name__ == '__main__':
    # test on data from the Civic monitoring station
    analyse('aqi_data_civic.csv')

    # test on data from the Florey monitoring station
    #analyse('aqi_data_florey.csv')

    # test on data from the Monash monitoring station
    #analyse('aqi_data_monash.csv')
